#STAGE 1
FROM node:16 AS build

LABEL Description="ugmk_test_app"

WORKDIR /usr/src/app

COPY package.json ./

ENV NODE_OPTIONS="--max-old-space-size=8192"

RUN npm install

COPY . .

RUN npm run build

#STAGE 2
FROM nginx:1.23.4

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/build /usr/share/nginx/html
